# Site settings
title: kEEPpp's CV
description: A CV/Resume template for developers.
baseurl: "/CV"
url: "https://kEEPpp.github.io"

# User settings - Update with your information
username: Your Name
user_description: Describe yourself here.
user_title: Your Title (e.g., Software Engineer)
email: your.email@example.com
github_username:  kEEPpp

# Build settings - Do not change
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins - Do not change
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

# Others - Do not change
paginate: 10
paginate_path: "/blog/page:num/"
